[package]
name = "test_undetected_chromedrive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
undetected-chromedriver = "0.1.2"
